# Generated by Django 4.0.2 on 2022-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Sent', 'Sent')], default='Sent', max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='store.OrderItem')),
            ],
        ),
    ]
