# Generated by Django 4.0.2 on 2022-11-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_refund_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
