# Generated by Django 4.0.2 on 2022-12-05 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rated_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
