# Generated by Django 4.0.2 on 2022-12-05 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_rated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='combined_rating',
            field=models.DecimalField(decimal_places=1, default=9, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
