# Generated by Django 4.0.2 on 2023-02-25 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rated_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
