# Generated by Django 4.0.2 on 2022-11-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user-img.png', upload_to='avatar'),
        ),
    ]
