# Generated by Django 4.0.2 on 2022-11-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
