# Generated by Django 4.0.2 on 2022-11-07 20:18

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=25, validators=[blog.validators.restrict_vulger_words, blog.validators.validate_name]),
        ),
    ]
