# Generated by Django 4.0.2 on 2022-11-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profile_pic',
            new_name='avatar',
        ),
    ]
