# Generated by Django 4.0.2 on 2022-12-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_author_github_author_linkedin_author_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.CharField(help_text='your state, country', max_length=30, null=True),
        ),
    ]
