# Generated by Django 4.0.2 on 2023-04-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpost',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
