# Generated by Django 4.0.2 on 2023-05-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_featuredpost_github_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
